# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Apuntes de Electromagnetismo II
author: Guillermo Fernando Regodon Harkness
copyright: "2025"
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default! See here: https://jupyterbook.org/en/stable/customize/config.html
    - dollarmath

    # Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib
  
